import Link from 'next/link';
import { ArrowRight, CheckCircle2, Globe2, MapPin, Search, ShieldCheck, TrendingUp } from 'lucide-react';

const projects = [
  { name: 'Pasig River Recovery', country: 'Philippines', type: 'Plastic recovery', metric: '12,480 t', available: '4,218 t', price: '€92 / tonne', verification: 'PPRS verified', className: 'river' },
  { name: 'Katingan Forest Restoration', country: 'Indonesia', type: 'Carbon removal', metric: '48,210 tCO₂', available: '11,600 tCO₂', price: '€28 / tCO₂', verification: 'Third-party verified', className: 'forest' },
  { name: 'Clean Coast Tamil Nadu', country: 'India', type: 'Ocean recovery', metric: '3,840 t', available: '1,180 t', price: '€118 / tonne', verification: 'OBP verified', className: 'coast' },
];
function Logo(){return <div className="logo" aria-label="PRX Markets"><span>PR</span><span className="xmark"><i></i><b></b></span><small>MARKETS</small></div>}
export default function Home(){return <main>
<nav><Logo/><div className="navlinks"><Link href="/projects">Projects</Link><a href="#impact">Impact</a><a href="#how">How it works</a><a href="#business">For business</a><a href="#registry">Registry</a></div><div className="navright"><Search size={18}/><button className="ghost">Log in</button><Link href="/projects"><button>Open market</button></Link></div></nav>
<section className="hero"><div className="heroGlow"></div><div className="gridlines"></div><div className="eyebrow"><span></span> PLANETARY RECOVERY EXCHANGE</div><h1>Fund what<br/>gets <em>fixed.</em></h1><p>A global market for verified environmental recovery. Real projects. Measurable impact. Transparent evidence.</p><div className="actions"><Link href="/projects"><button>Explore projects <ArrowRight size={17}/></button></Link><button className="outline">How PRX works</button></div><div className="heroAside"><p>CAPITAL FLOWS<br/>TO REAL IMPACT.</p><span>People · Capital · Projects · Recovery</span></div></section>
<section className="ticker" id="impact"><div><TrendingUp/><strong>1,284,922</strong><span>TONNES RECOVERED</span></div><div><MapPin/><strong>312</strong><span>PROJECTS</span></div><div><Globe2/><strong>28</strong><span>COUNTRIES</span></div><div><ShieldCheck/><strong>842</strong><span>VERIFIED RECORDS</span></div></section>
<section className="market" id="projects"><div className="sectionHead"><div><div className="eyebrow"><span></span> RECOVERY MARKET</div><h2>Capital for measurable recovery.</h2></div><p>Discover projects by recovery type, geography and verification standard. Every funded unit is traceable from capital to outcome.</p></div><div className="categories"><article><span>01</span><h3>PLASTIC</h3><p>Recover and recycle plastic waste.</p></article><article><span>02</span><h3>CARBON</h3><p>Remove and store CO₂ durably.</p></article><article><span>03</span><h3>FORESTS</h3><p>Restore ecosystems and biodiversity.</p></article><article><span>04</span><h3>OCEANS</h3><p>Clean and protect marine systems.</p></article></div></section>
<section className="mapSection"><div className="mapCopy"><div className="eyebrow"><span></span> GLOBAL NETWORK</div><h2>Recovery,<br/>mapped.</h2><p>Explore where capital is turning into physical, verified environmental outcomes.</p><Link href="/projects"><button className="outline">Open project market <ArrowRight size={16}/></button></Link></div><div className="world"><div className="worldText">PRX / GLOBAL RECOVERY NETWORK</div>{[[17,33],[25,44],[31,27],[40,51],[49,38],[56,55],[63,30],[68,61],[75,44],[81,65],[88,49]].map((p,i)=><i key={i} style={{left:`${p[0]}%`,top:`${p[1]}%`}}></i>)}</div></section>
<section className="featured"><div className="sectionHead"><div><div className="eyebrow"><span></span> VERIFIED SUPPLY</div><h2>Featured projects</h2></div><Link href="/projects"><button className="textButton">View all projects <ArrowRight size={16}/></button></Link></div><div className="cards">{projects.map(p=><article className="card" key={p.name}><div className={`projectImage ${p.className}`}><span>{p.type}</span></div><div className="cardBody"><div className="country">{p.country}</div><h3>{p.name}</h3><div className="verified"><CheckCircle2 size={15}/>{p.verification}</div><div className="metrics"><div><strong>{p.metric}</strong><span>recovered</span></div><div><strong>{p.available}</strong><span>available</span></div></div><div className="price"><strong>{p.price}</strong><button><ArrowRight size={18}/></button></div></div></article>)}</div></section>
<section className="mechanism" id="how"><div><div className="eyebrow"><span></span> THE PRX MECHANISM</div><h2>Capital in.<br/><em>Recovery out.</em></h2></div><div className="flow"><span>CAPITAL</span><i></i><span>PROJECTS</span><i></i><span>VERIFICATION</span><i></i><span className="active">RECOVERY</span></div><p>PRX connects capital with verified environmental projects, records the evidence and makes every funded outcome visible in a public registry.</p></section>
<section className="registry" id="registry"><div><div className="eyebrow"><span></span> PUBLIC REGISTRY</div><h2>Don't tell us it's green.<br/>Show us what happened.</h2><p>Every PRX recovery record links funding, project, methodology, evidence, verification and retirement in one auditable chain.</p></div><div className="record"><header><Logo/><span>RECOVERY RECORD / PRX-26-004218</span></header><div className="recordGrid"><span>PROJECT<small>Pasig River Recovery</small></span><span>RECOVERY<small>10.00 tonnes</small></span><span>STATUS<small className="cyan">● VERIFIED</small></span><span>FUNDED<small>16 Sep 2026</small></span></div><div className="hash">EVIDENCE CHAIN&nbsp;&nbsp; 0x92F4 · 12 DOCUMENTS · VERIFIED</div></div></section>
<section className="cta" id="business"><div className="eyebrow"><span></span> PRX FOR BUSINESS</div><h2>Put capital to work<br/>where it can be measured.</h2><p>Build a recovery portfolio across plastic, carbon, forests and oceans—with evidence your customers and stakeholders can inspect.</p><Link href="/projects"><button>Enter the market <ArrowRight size={17}/></button></Link></section><footer><Logo/><p>Markets for measurable recovery.</p><div>© 2026 PRX Markets <span>·</span> Amsterdam</div></footer></main>}
